### ISSUE TITLE
FileNotFoundException  lib\src.zip

### ISSUE THREAD

**Issue by ronniegward** [ghaffarian/progex#12]
The directory which is being scanned by progex does not have a reference to "src.zip" so I'm not sure how to chase the bug from a user perspective. Attached is a progex.log file showing the bug occurring. Aside from -info, it also happens with -cfg and -icfg. This code is great work! Thank you for posting it!
[progex.log](https://github.com/ghaffarian/progex/files/4308498/progex.log)

**Comment by ghaffarian** [comment]
Hi;
The file you provided shows no errors. It only shows that you didn't provide any input path for PROGEX to analyze program files.

If you obtain the latest version of PROGEX from the releases page, you should have no problem running the tool. Please follow the examples in the help message of PROGEX.

**Comment by ronniegward** [comment]
I found a work around for the bug (and the issue is not that I didn't provide an input path--I did). When using -icfg, for example, progex ignores the given input path, and searches the current working directory for a folder named lib and a compressed file named "src.zip." Works like a champ. Nice product. Thank you for developing it!

**Comment by taowangcheng** [comment]
@ronniegward 
Can you successfully generate the icfg graph? Hope you can share your approach.
thank you very much!
