### ISSUE TITLE
mvn compilation problem

### ISSUE THREAD

**Issue by omah69** [ghaffarian/progex#5]
Hello, 

Does the "mvn install" works well to build the source code ? 
Personaly, I have problem with th none-logger and graphs dependencies ...

**Comment by ghaffarian** [comment]
Hi;
The [`Nano-Logger`](https://github.com/ghaffarian/nanologger) and [`Graphs`](https://github.com/ghaffarian/graphs) projects are not available through Maven Central. So you first need to clone those two repositories and do `mvn install` inside each of them. Then do `mvn clean install` for [`PROGEX`](https://github.com/ghaffarian/progex).

**Comment by ghaffarian** [comment]
If the previous comment fixes your problem, consider closing this issue.
